require_relative '../../../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBluetoothLe', :path => '../../../../../node_modules/@capacitor-community/bluetooth-le'
  pod 'CapacitorCommunityCameraPreview', :path => '../../../../../node_modules/@capacitor-community/camera-preview'
  pod 'CapacitorCommunityGenericOauth2', :path => '../../../../../node_modules/@capacitor-community/generic-oauth2'
  pod 'CapacitorCommunityImageToText', :path => '../../../../../node_modules/@capacitor-community/image-to-text'
  pod 'CapacitorApp', :path => '../../../../../node_modules/@capacitor/app'
  pod 'CapacitorBarcodeScanner', :path => '../../../../../node_modules/@capacitor/barcode-scanner'
  pod 'CapacitorBrowser', :path => '../../../../../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../../../../node_modules/@capacitor/camera'
  pod 'CapacitorDevice', :path => '../../../../../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../../../../node_modules/@capacitor/geolocation'
  pod 'CapacitorKeyboard', :path => '../../../../../node_modules/@capacitor/keyboard'
  pod 'CapacitorShare', :path => '../../../../../node_modules/@capacitor/share'
  pod 'CapawesomeCapacitorFilePicker', :path => '../../../../../node_modules/@capawesome/capacitor-file-picker'
  pod 'CapgoCapacitorNativeBiometric', :path => '../../../../../node_modules/@capgo/capacitor-native-biometric'
  pod 'CapacitorDocumentScanner', :path => '../../../../../node_modules/capacitor-document-scanner'
  pod 'CapacitorEmailComposer', :path => '../../../../../node_modules/capacitor-email-composer'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
